
CREATE DATABASE  IF NOT EXISTS `SCHOOL_A` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `SCHOOL_A`;

DROP TABLE IF EXISTS `ACCOUNT_LOAN`;
CREATE TABLE IF NOT EXISTS`SCHOOL_A.ACCOUNT_LOAN` (
  `ACCOUNT_NUMBER`  varchar(45) NOT NULL,
  `ACCOUNT_TYPE` varchar(45) NOT NULL,
`DOCUMENT_NUMBER` varchar(45) NOT NULL,
`EFFECTIVE_DATE` varchar(45) NOT NULL,
`TRANSACTION_AMOUNT` numeric(8,2) NOT NULL,
  PRIMARY KEY (`ACCOUNT_NUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `SCHOOL_A.ACCOUNT_LOAN` VALUES (‘123456’,’SAVING’,’25235235’,’2012-12-12’,1000.5);


LOCK TABLES `STUDENT` WRITE;
/*!40000 ALTER TABLE `STUDENT` DISABLE KEYS */;
INSERT INTO `STUDENT` VALUES (1,'BOSS'),(2,'MOO');
/*!40000 ALTER TABLE `STUDENT` ENABLE KEYS */;
UNLOCK TABLES;